### PR TITLE
Singularity

### PR DESCRIPTION
**Pull request by nllong**
Add singularity build process. Includes another Dockerfile to run the singularity build process. This is a manual build process at the moment.

### CODE REVIEW

**Comment by nmerket** [comment]
@nllong This looks great. So does that mean the singularity images will automagically be pushed to an S3 bucket on a new OS release?

**Comment by nmerket** [comment]
I just tried this image on peregrine. I'm getting the following error when I call the OS cli:

```
Singularity docker-openstudio.simg:~/OpenStudio-BEopt> openstudio

Error: locale::facet::_S_create_c_locale name not valid
Backtrace:
	:/openstudio_cli.rb:33:in `application'
	:/openstudio_cli.rb:33:in `<main>'
	eval:107:in `eval'
	eval:107:in `require_embedded_absolute'
	eval:92:in `block in require'
	eval:86:in `each'
	eval:86:in `require'
	eval:2:in `<main>'
Exception: locale::facet::_S_create_c_locale name not valid
<main>: unexpected return
```

**Comment by nmerket** [comment]
The weird thing is that it doesn't do that when I run singularity on my local machine (within docker).

**Comment by nmerket** [comment]
I think it has something to do with this issue https://github.com/singularityware/singularity/issues/1074. When I run the file locally I get the following warning:

```
WARNING: Non existent 'bind path' source: '/etc/localtime'
```

On peregrine there is no such warning but it complains about the locale not being valid when I try to run the `openstudio` command line program. They seem related.

**Comment by nllong** [comment]
Yeah, the goal is to have them along side the other installers:

image

I'll need to dive into the localtime. From a quick search, that doesn't appear to break all containers.

**Comment by nllong** [comment]
@nmerket -- it looks like if you start bash after launching the container then it works. I am trying to figure out why and if there is anything we can do to make this automatic.

```
Singularity OpenStudio-2.6.0.ac20db5eff-Singularity.simg:~> bash
nlong@login2:~$ cat /etc/issue
Ubuntu 14.04.5 LTS \n \l

nlong@login2:~$ openstudio --help
Usage: openstudio [options] <command> [<args>]

    -h, --help                       Print this help.
        --verbose                    Print the full log to STDOUT
        --no-ssl                     Skip initializing SSL
    -I, --include DIR                Add additional directory to add to front of Ruby $LOAD_PATH (may be used more than once)
    -e, --execute CMD                Execute one line of script (may be used more than once). Returns after executing commands.
        --gem_path DIR               Add additional directory to add to front of GEM_PATH environment variable (may be used more than once)
        --gem_home DIR               Set GEM_HOME environment variable

Common commands:
     energyplus_version   Returns the EnergyPlus version used by the CLI
     list_commands        Lists the entire set of available commands
     measure              Updates measures and compute arguments
     openstudio_version   Returns the OpenStudio version used by the CLI
     run                  Executes an OpenStudio Workflow file
     update               Updates OpenStudio Models to the current version

For help on any individual command run `openstudio COMMAND -h`

Additional commands are available, but are either more advanced
or not commonly used. To see all commands, run the command
`openstudio list_commands`.
nlong@login2:~$
```

**Comment by nllong** [comment]
Okay. this appears to be fixed now -- thanks to a mongodb post about the same issue.

```
[nlong@login3 ~]$ singularity exec -B /scratch:/scratch OpenStudio-2.6.0.ac20db5eff-Singularity.simg openstudio openstudio_version
2.6.0.ac20db5eff
```

**Pull request merged**
